"""LLM-модуль MedNews Secretary Agent."""

from app.llm.prompts import (
    INTENT_CLASSIFICATION_SYSTEM_PROMPT,
    NEWS_ANALYSIS_SYSTEM_PROMPT,
    REMINDER_SUMMARY_SYSTEM_PROMPT,
)

__all__ = [
    "INTENT_CLASSIFICATION_SYSTEM_PROMPT",
    "NEWS_ANALYSIS_SYSTEM_PROMPT",
    "REMINDER_SUMMARY_SYSTEM_PROMPT",
]
